version: "3.7"

services:
  mautrix-telegram:
    container_name: mautrix-telegram
    image: mautrix-telegram-custom
    restart: unless-stopped
    volumes:
    - $PWD/data:/data:Z # :Z is only for SELinux-enabled systems like Fedora. Remove if necessary.
    networks:
    - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
