version: '3.3'

services:
  matrix-server:
    image: matrixdotorg/synapse
    container_name: matrix-synapse
    restart: always
    volumes:
      - $PWD/data:/data:Z # :Z is only for SELinux-enabled systems like Fedora. Remove if necessary.
    labels:
      - "traefik.enable=true"
      - "traefik.port=8008"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.matrix-synapse.entrypoints=websecure"
      - "traefik.http.routers.matrix-synapse.rule=Host(`yourhostname`)" # Put in your hostname here, e.g. subdomain.domain.tld
      - "traefik.http.routers.matrix-synapse.tls.certresolver=mytlschallenge"
    networks:
      - webproxy
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
networks:
  webproxy:
    external:
      name: webproxy
